server.port=8080

# SQLite configuration
spring.datasource.url=jdbc:sqlite:devpulse.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# General settings
spring.main.banner-mode=off
logging.level.org.hibernate.SQL=DEBUG
